### ISSUE TITLE
Where can we find the static video ？ thanks！

### ISSUE THREAD

**Issue by yangmuzhi** [Th3NiKo/Football-players-detection#1]

**Comment by Th3NiKo** [comment]
Below is sample of low quality static video. It is good video for getting some sense of alghoritms.
[Google drive sample static video](https://drive.google.com/file/d/1AfZjTKG3le_1MTOvFHcOUIhk51u1JraU/view)

**Comment by yangmuzhi** [comment]
Thank you : )
